#+title: Readme
#+Author: Pascal Jaeger
#+OPTIONS: toc:3

* Table of contents :TOC_3_gh:QUOTE:
#+BEGIN_QUOTE
- [[#installation][Installation]]
  - [[#adding-the-repository][Adding the repository]]
    - [[#with-eselect-repository][With eselect-repository]]
    - [[#manually][Manually]]
  - [[#installing-the-launcher][Installing the launcher]]
  - [[#fixing-crash-when-opening-config][Fixing crash when opening config]]
- [[#uninstallation][Uninstallation]]
#+END_QUOTE

* Installation
** Adding the repository
To install one of the launchers with Portage, you have to add this github repo
into portage's repositories.

*** With eselect-repository
If you haven't already, emerge [[https://wiki.gentoo.org/wiki/Eselect/Repository][eselect-repository]] with

#+begin_src bash
emerge --ask app-eselect/eselect-repository
#+end_src

Now add the repository with

#+begin_src bash
eselect repository add The-Anime-Game git https://github.com/an-anime-team/aagl-ebuilds.git
emaint sync -r The-Anime-Game
#+end_src

*** Manually
If /etc/portage/repos.conf is a file, add the following lines to that
file, if /etc/portage/repos.conf is a directory, add a new file with
file ~touch /etc/portage/repos.conf/theanimegame.conf~ and put the
following into it:

#+begin_src bash
[The-Anime-Game]
location = /var/db/repos/theanimegame
sync-type = git
sync-uri = https://github.com/an-anime-team/aagl-ebuilds.git
priority = 100
#+end_src

Then sync your local ebuild cache with ~emerge --sync~

** Installing the launcher
After adding the repository you can emerge the launcher. There are
currently two different versions of the launcher available as ebuilds,
[[https://github.com/an-anime-team/an-anime-game-launcher][the typescript version]] and the [[https://github.com/an-anime-team/an-anime-game-launcher-gtk][Rust/ Gtk version]]. Visit their respective
repos for further information on them.

#+begin_src bash
emerge --ask games-misc/an-anime-game-launcher-bin # for the typescript version
# OR
emerge --ask games-misc/an-anime-game-launcher-gtk # for the gtk version
#+end_src

This can take a while if you don't have wine installed.

** Fixing crash when opening config
If the launcher crashes when you click on the little cog wheel to open the config, it is likely because it can not find the folder where different versions of dxvk should be stored. (See also https://github.com/an-anime-team/an-anime-game-launcher-gtk/issues/3)
Check if the folder ~~/.local/share/anime-game-launcher/dxvks~ exists and if not, create it with
#+begin_src bash
mkdir ~/.local/share/anime-game-launcher/dxvks
#+end_src

* Uninstallation
To uninstall just deselect the package and run a depclean

#+begin_src bash
emerge --deselect an-anime-game-launcher-bin # if you installed the typescript version before
#OR
emerge --deselect an-anime-game-launcher-gtk # if you installed the gtk version before

# in both cases depclean to remove the unneeded packages
emerge --depclean
#+end_src

And remove the repository with

#+begin_src bash
rm /etc/portage/repos.conf/theanimegame.conf # if the repository was manually added
#OR
eselect repository disable -f The-Anime-Game # if the repository was added via eselect
#+end_src
