#+title: Readme
#+Author: Pascal Jaeger
#+OPTIONS: toc:3

* Table of contents :TOC_3_gh:QUOTE:
#+BEGIN_QUOTE
- [[#installation][Installation]]
  - [[#adding-the-repository][Adding the repository]]
    - [[#with-eselect-repository][With eselect-repository]]
    - [[#manually][Manually]]
  - [[#installing-the-launcher][Installing the launcher]]
  - [[#fixing-crash-when-opening-config][Fixing crash when opening config]]
- [[#uninstallation][Uninstallation]]
- [[#trouble-after-gitlab-migration--syncing-trouble-in-general][Trouble after Gitlab migration / syncing trouble in general]]
#+END_QUOTE

* Installation
** Adding the repository
To install one of the launchers with Portage, you have to add this github repo
into portage's repositories.

*** With eselect-repository
If you haven't already, emerge [[https://wiki.gentoo.org/wiki/Eselect/Repository][eselect-repository]] with

#+begin_src bash
emerge --ask app-eselect/eselect-repository
#+end_src

Now add the repository with

#+begin_src bash
eselect repository add an-anime-team git https://github.com/an-anime-team/aagl-ebuilds.git
emaint sync -r an-anime-team
#+end_src

*** Manually
If /etc/portage/repos.conf is a file, add the following lines to that
file, if /etc/portage/repos.conf is a directory, add a new file with
~touch /etc/portage/repos.conf/ananimeteam.conf~ and put the
following into it:

#+begin_src bash
[an-anime-team]
location = /var/db/repos/ananimeteam
sync-type = git
sync-uri = https://github.com/an-anime-team/aagl-ebuilds.git
priority = 100
#+end_src

Then sync your local ebuild cache with ~emaint sync -r an-anime-game~

** Installing the launcher
After adding the repository you can emerge the launcher.
#+begin_src bash
emerge --ask games-misc/an-anime-game-launcher
#+end_src

** Fixing crash when opening config
If the launcher crashes when you click on the little cog wheel to open the config, it is likely because it can not find the folder where different versions of dxvk should be stored. (See also https://github.com/an-anime-team/an-anime-game-launcher-gtk/issues/3)
Check if the folder ~~/.local/share/anime-game-launcher/dxvks~ exists and if not, create it with
#+begin_src bash
mkdir ~/.local/share/anime-game-launcher/dxvks
#+end_src

* Uninstallation
To uninstall just deselect the package and run a depclean
#+begin_src bash
emerge --deselect an-anime-game-launcher

# in all cases depclean to remove the unneeded packages
emerge --depclean
#+end_src

To remove the whole repository from your system execute:
#+begin_src bash
rm /etc/portage/repos.conf/ananimeteam.conf # if the repository was manually added
#OR
eselect repository disable -f an-anime-team # if the repository was added via eselect
#+end_src

* Trouble after Gitlab migration / syncing trouble in general
If the original Gitlab repository was used before, there could be some issues with the migration to a new repository.
Also if you can not sync the repository because of a git issue, this could be helpful.
First of all, delete the old repository files:
#+begin_src bash
rm -rf /var/db/repos/The-Anime-Game
#+end_src

Then purge the repository this is done differently, depending on how you installed the repository before.
#+begin_src bash
rm /etc/portage/repos.conf/ananimeteam.conf # if the repository was manually added
#OR
eselect repository disable -f an-anime-team # if the repository was added via eselect
#+end_src

Now add the new repository according to the instructions in the [[Installation]] section.
